[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc-version = "0.8.25"

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "src/=src/",
    "script/=script/",
    "test/=test/"
]
